version: "3"

vars:
  TITLE: SipPuff
  DEFAULT_REGION: eastus2

tasks:
  default:
    cmds:
      - task --list

  init:
    desc: Initializes Terraform for {{.TITLE}} Azure environment
    cmds:
      - terraform workspace new {{.REGION}} || true
      - terraform workspace select {{.REGION}}
      - terraform init
    vars:
      REGION: "{{default .DEFAULT_REGION .CLI_ARGS}}"

  up:
    desc: Creates full Azure environment for {{.TITLE}}
    cmds:
      - task: init
      - task: apply
    vars:
      REGION: "{{default .DEFAULT_REGION .CLI_ARGS}}"

  apply:
    desc: Applies Terraform configuration for {{.TITLE}}
    cmds:
      - terraform apply -auto-approve -compact-warnings
        -var "region={{.REGION}}"
        -var "tags={{.TITLE}}"
    vars:
      REGION: "{{default .DEFAULT_REGION .CLI_ARGS}}"

  plan:
    desc: Plans Terraform changes for {{.TITLE}}
    cmds:
      - terraform plan
        -var "region={{.REGION}}"
        -var "tags={{.TITLE}}"
    vars:
      REGION: "{{default .DEFAULT_REGION .CLI_ARGS}}"

  output:
    desc: Shows Terraform outputs for {{.TITLE}}
    cmds:
      - terraform output

  down:
    desc: Destroys all Azure resources and cleans up Terraform for {{.TITLE}}
    cmds:
      - az group list --tag Application="{{.TITLE}}" --query "[].name" -o tsv | xargs -ot -n 1 az group delete -y --no-wait -n || true
      - rm -rf terraform.tfstate.d .terraform.lock.hcl .terraform terraform.tfstate terraform.tfstate.backup .terraform.tfstate.lock.info || true